import type { AIDesignTokens } from '~/schemas/ai-design-tokens'

export interface VibePreset {
  id: string
  label: string
  description: string
  tokens: AIDesignTokens
}

export const VIBE_PRESETS: VibePreset[] = [
  // ── 1. Dark & Moody ──────────────────────────────────────────────────
  {
    id: 'dark-moody',
    label: 'Dark & Moody',
    description: 'Deep shadows, dramatic lighting, rich dark tones',
    tokens: {
      colors: {
        primary: '#1a1a2e',
        secondary: '#16213e',
        accent: '#e94560',
        background: '#0f0f0f',
        surface: '#1a1a1a',
        text: '#e0e0e0',
        textMuted: '#888888',
        heading: '#ffffff',
        link: '#e94560',
        border: '#2a2a2a',
        error: '#ef4444',
        success: '#22c55e',
      },
      typography: {
        display: { fontFamily: 'Bebas Neue', fontSize: '5rem', fontWeight: '400', textTransform: 'uppercase' },
        h1: { fontFamily: 'Bebas Neue', fontSize: '2.5rem', fontWeight: '400', textTransform: 'uppercase' },
        h2: { fontFamily: 'Inter', fontSize: '1.5rem', fontWeight: '600' },
        h3: { fontFamily: 'Inter', fontSize: '1.25rem', fontWeight: '600' },
        h4: { fontFamily: 'Inter', fontSize: '1rem', fontWeight: '600' },
        body: { fontFamily: 'Inter', fontSize: '1rem', fontWeight: '400', lineHeight: '1.7' },
        small: { fontFamily: 'Inter', fontSize: '0.875rem', fontWeight: '400' },
        caption: { fontFamily: 'Inter', fontSize: '0.75rem', fontWeight: '500', textTransform: 'uppercase', letterSpacing: '0.05em' },
      },
      fontImports: ['Bebas Neue', 'Inter'],
      spacing: { xs: '0.25rem', sm: '0.5rem', md: '1rem', lg: '2rem', xl: '4rem', '2xl': '6rem' },
      radii: { none: '0', sm: '0.25rem', md: '0.5rem', lg: '1rem', full: '9999px' },
      shadows: {
        none: 'none',
        sm: '0 1px 3px rgba(0,0,0,0.3)',
        md: '0 4px 12px rgba(0,0,0,0.4)',
        lg: '0 8px 24px rgba(0,0,0,0.5)',
        xl: '0 16px 48px rgba(0,0,0,0.6)',
      },
      animation: { sectionEntrance: 'fade', duration: '0.6s', easing: 'ease-out' },
      layout: {
        contentWidth: '72rem',
        sectionPadding: '5rem',
        sectionOrder: ['hero', 'bio', 'music', 'events', 'photos', 'contact'],
        sectionVisibility: { hero: true, bio: true, music: true, events: true, photos: true, contact: true },
        navStyle: 'fixed',
        footerStyle: 'minimal',
      },
      sections: {
        hero: { variant: 'fullscreen', overlayOpacity: 0.6, titleAlignment: 'center', showSubtitle: true, showGenres: true },
        bio: { variant: 'centered', showReadMore: true, maxLines: 6 },
        music: { variant: 'cards', columnsDesktop: 3, showCoverArt: true, showDuration: true },
        events: { variant: 'timeline', showPastEvents: false, maxVisible: 8 },
        photos: { variant: 'masonry', columnsDesktop: 3, gap: '0.5rem', aspectRatio: 'auto' },
        contact: { variant: 'form', showSocialLinks: true },
      },
      decorative: {
        dividerStyle: 'none',
        backgroundPattern: 'none',
        buttonStyle: 'square',
        linkStyle: 'hover-underline',
        cardBorder: 'subtle',
        shadow: 'lg',
      },
    },
  },

  // ── 2. Clean & Minimal ───────────────────────────────────────────────
  {
    id: 'clean-minimal',
    label: 'Clean & Minimal',
    description: 'Whites, light grays, simple typography, lots of whitespace',
    tokens: {
      colors: {
        primary: '#111111',
        secondary: '#555555',
        accent: '#0066ff',
        background: '#ffffff',
        surface: '#f8f8f8',
        text: '#333333',
        textMuted: '#999999',
        heading: '#111111',
        link: '#0066ff',
        border: '#e5e5e5',
        error: '#dc2626',
        success: '#16a34a',
      },
      typography: {
        display: { fontFamily: 'Inter', fontSize: '4rem', fontWeight: '300', lineHeight: '1.1', letterSpacing: '-0.02em' },
        h1: { fontFamily: 'Inter', fontSize: '2.25rem', fontWeight: '300', lineHeight: '1.2', letterSpacing: '-0.01em' },
        h2: { fontFamily: 'Inter', fontSize: '1.5rem', fontWeight: '500', lineHeight: '1.3' },
        h3: { fontFamily: 'Inter', fontSize: '1.25rem', fontWeight: '500' },
        h4: { fontFamily: 'Inter', fontSize: '1rem', fontWeight: '500' },
        body: { fontFamily: 'Inter', fontSize: '1rem', fontWeight: '400', lineHeight: '1.8' },
        small: { fontFamily: 'Inter', fontSize: '0.875rem', fontWeight: '400' },
        caption: { fontFamily: 'Inter', fontSize: '0.75rem', fontWeight: '400', letterSpacing: '0.02em' },
      },
      fontImports: ['Inter'],
      spacing: { xs: '0.5rem', sm: '1rem', md: '1.5rem', lg: '3rem', xl: '5rem', '2xl': '8rem' },
      radii: { none: '0', sm: '0.25rem', md: '0.5rem', lg: '0.75rem', full: '9999px' },
      shadows: {
        none: 'none',
        sm: '0 1px 2px rgba(0,0,0,0.04)',
        md: '0 2px 8px rgba(0,0,0,0.06)',
        lg: '0 4px 16px rgba(0,0,0,0.08)',
        xl: '0 8px 32px rgba(0,0,0,0.1)',
      },
      animation: { sectionEntrance: 'fade', duration: '0.4s', easing: 'ease' },
      layout: {
        contentWidth: '64rem',
        sectionPadding: '6rem',
        sectionOrder: ['hero', 'bio', 'music', 'events', 'photos', 'contact'],
        sectionVisibility: { hero: true, bio: true, music: true, events: true, photos: true, contact: true },
        navStyle: 'fixed',
        footerStyle: 'minimal',
      },
      sections: {
        hero: { variant: 'minimal', titleAlignment: 'left', showSubtitle: true, showGenres: false },
        bio: { variant: 'full-width', showReadMore: false, maxLines: 10 },
        music: { variant: 'list', columnsDesktop: 1, showCoverArt: true, showDuration: true },
        events: { variant: 'list', showPastEvents: false, maxVisible: 6 },
        photos: { variant: 'grid', columnsDesktop: 3, gap: '1rem', aspectRatio: 'square' },
        contact: { variant: 'minimal', showSocialLinks: true },
      },
      decorative: {
        dividerStyle: 'line',
        backgroundPattern: 'none',
        buttonStyle: 'rounded',
        linkStyle: 'hover-underline',
        cardBorder: 'none',
        shadow: 'none',
      },
    },
  },

  // ── 3. Neon Electric ─────────────────────────────────────────────────
  {
    id: 'neon-electric',
    label: 'Neon Electric',
    description: 'Dark backgrounds, vibrant neon accents, glowing effects',
    tokens: {
      colors: {
        primary: '#0a0a0f',
        secondary: '#12121a',
        accent: '#00ff88',
        background: '#060609',
        surface: '#0f0f18',
        text: '#c8c8d0',
        textMuted: '#6b6b80',
        heading: '#ffffff',
        link: '#00ff88',
        border: '#1a1a2e',
        error: '#ff3366',
        success: '#00ff88',
      },
      gradients: [
        { type: 'linear', angle: 135, stops: [{ color: '#00ff88', position: 0 }, { color: '#00ccff', position: 100 }] },
        { type: 'linear', angle: 45, stops: [{ color: '#ff00ff', position: 0 }, { color: '#00ff88', position: 100 }] },
      ],
      typography: {
        display: { fontFamily: 'Space Grotesk', fontSize: '5rem', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '-0.02em' },
        h1: { fontFamily: 'Space Grotesk', fontSize: '2.5rem', fontWeight: '700', textTransform: 'uppercase' },
        h2: { fontFamily: 'Space Grotesk', fontSize: '1.5rem', fontWeight: '600' },
        h3: { fontFamily: 'Space Grotesk', fontSize: '1.25rem', fontWeight: '600' },
        h4: { fontFamily: 'Space Grotesk', fontSize: '1rem', fontWeight: '600' },
        body: { fontFamily: 'DM Sans', fontSize: '1rem', fontWeight: '400', lineHeight: '1.7' },
        small: { fontFamily: 'DM Sans', fontSize: '0.875rem', fontWeight: '400' },
        caption: { fontFamily: 'JetBrains Mono', fontSize: '0.75rem', fontWeight: '400', textTransform: 'uppercase', letterSpacing: '0.08em' },
      },
      fontImports: ['Space Grotesk', 'DM Sans', 'JetBrains Mono'],
      spacing: { xs: '0.25rem', sm: '0.5rem', md: '1rem', lg: '2rem', xl: '4rem', '2xl': '6rem' },
      radii: { none: '0', sm: '0.25rem', md: '0.5rem', lg: '1rem', full: '9999px' },
      shadows: {
        none: 'none',
        sm: '0 0 8px rgba(0,255,136,0.15)',
        md: '0 0 16px rgba(0,255,136,0.2)',
        lg: '0 0 32px rgba(0,255,136,0.25)',
        xl: '0 0 64px rgba(0,255,136,0.3)',
      },
      animation: { sectionEntrance: 'slide-up', duration: '0.5s', easing: 'cubic-bezier(0.16,1,0.3,1)' },
      layout: {
        contentWidth: '72rem',
        sectionPadding: '5rem',
        sectionOrder: ['hero', 'bio', 'music', 'events', 'photos', 'contact'],
        sectionVisibility: { hero: true, bio: true, music: true, events: true, photos: true, contact: true },
        navStyle: 'fixed',
        footerStyle: 'minimal',
      },
      sections: {
        hero: { variant: 'fullscreen', overlayOpacity: 0.7, titleAlignment: 'center', showSubtitle: true, showGenres: true },
        bio: { variant: 'centered', showReadMore: true, maxLines: 5 },
        music: { variant: 'waveform', columnsDesktop: 2, showCoverArt: true, showDuration: true },
        events: { variant: 'grid', showPastEvents: false, maxVisible: 6 },
        photos: { variant: 'grid', columnsDesktop: 4, gap: '0.25rem', aspectRatio: 'square' },
        contact: { variant: 'card', showSocialLinks: true },
      },
      decorative: {
        dividerStyle: 'gradient',
        backgroundPattern: 'grid',
        accentElements: {
          glow: { enabled: true, color: '#00ff88', blur: '80px' },
        },
        buttonStyle: 'pill',
        linkStyle: 'none',
        cardBorder: 'subtle',
        shadow: 'md',
      },
    },
  },

  // ── 4. Warm & Organic ────────────────────────────────────────────────
  {
    id: 'warm-organic',
    label: 'Warm & Organic',
    description: 'Earth tones, serif fonts, warm textures and shadows',
    tokens: {
      colors: {
        primary: '#3d2b1f',
        secondary: '#5c4033',
        accent: '#c8553d',
        background: '#faf5f0',
        surface: '#f0e8df',
        text: '#3d2b1f',
        textMuted: '#8c7a6e',
        heading: '#2a1a0e',
        link: '#c8553d',
        border: '#d9cfc4',
        error: '#b91c1c',
        success: '#3f6212',
      },
      typography: {
        display: { fontFamily: 'Playfair Display', fontSize: '4.5rem', fontWeight: '700', lineHeight: '1.1' },
        h1: { fontFamily: 'Playfair Display', fontSize: '2.5rem', fontWeight: '700', lineHeight: '1.2' },
        h2: { fontFamily: 'Playfair Display', fontSize: '1.75rem', fontWeight: '600' },
        h3: { fontFamily: 'Lora', fontSize: '1.25rem', fontWeight: '600' },
        h4: { fontFamily: 'Lora', fontSize: '1rem', fontWeight: '600' },
        body: { fontFamily: 'Lora', fontSize: '1.05rem', fontWeight: '400', lineHeight: '1.8' },
        small: { fontFamily: 'Lora', fontSize: '0.875rem', fontWeight: '400' },
        caption: { fontFamily: 'Lora', fontSize: '0.75rem', fontWeight: '500', letterSpacing: '0.03em' },
      },
      fontImports: ['Playfair Display', 'Lora'],
      spacing: { xs: '0.25rem', sm: '0.75rem', md: '1.25rem', lg: '2.5rem', xl: '4.5rem', '2xl': '7rem' },
      radii: { none: '0', sm: '0.375rem', md: '0.75rem', lg: '1.25rem', full: '9999px' },
      shadows: {
        none: 'none',
        sm: '0 1px 4px rgba(61,43,31,0.08)',
        md: '0 4px 12px rgba(61,43,31,0.12)',
        lg: '0 8px 24px rgba(61,43,31,0.16)',
        xl: '0 16px 40px rgba(61,43,31,0.2)',
      },
      animation: { sectionEntrance: 'fade', duration: '0.7s', easing: 'ease-in-out' },
      layout: {
        contentWidth: '64rem',
        sectionPadding: '5rem',
        sectionOrder: ['hero', 'bio', 'music', 'events', 'photos', 'contact'],
        sectionVisibility: { hero: true, bio: true, music: true, events: true, photos: true, contact: true },
        navStyle: 'static',
        footerStyle: 'detailed',
      },
      sections: {
        hero: { variant: 'split', overlayOpacity: 0.3, titleAlignment: 'left', showSubtitle: true, showGenres: true },
        bio: { variant: 'split-image', showReadMore: true, maxLines: 8 },
        music: { variant: 'featured', columnsDesktop: 2, showCoverArt: true, showDuration: true },
        events: { variant: 'list', showPastEvents: false, maxVisible: 5 },
        photos: { variant: 'masonry', columnsDesktop: 3, gap: '0.75rem', aspectRatio: 'auto' },
        contact: { variant: 'split', showSocialLinks: true },
      },
      decorative: {
        dividerStyle: 'wave',
        backgroundPattern: 'noise',
        buttonStyle: 'rounded',
        linkStyle: 'underline',
        cardBorder: 'subtle',
        shadow: 'md',
      },
    },
  },

  // ── 5. Retro Vintage ─────────────────────────────────────────────────
  {
    id: 'retro-vintage',
    label: 'Retro Vintage',
    description: 'Muted colors, retro fonts, textured feel',
    tokens: {
      colors: {
        primary: '#2d2a24',
        secondary: '#4a453c',
        accent: '#d4a574',
        background: '#f2ece3',
        surface: '#e8e0d4',
        text: '#3a3630',
        textMuted: '#7a7468',
        heading: '#2d2a24',
        link: '#b87333',
        border: '#c8bfb0',
        error: '#a83232',
        success: '#4a7c3f',
      },
      typography: {
        display: { fontFamily: 'Oswald', fontSize: '4.5rem', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.04em' },
        h1: { fontFamily: 'Oswald', fontSize: '2.5rem', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.03em' },
        h2: { fontFamily: 'Oswald', fontSize: '1.5rem', fontWeight: '500', textTransform: 'uppercase', letterSpacing: '0.02em' },
        h3: { fontFamily: 'Crimson Text', fontSize: '1.375rem', fontWeight: '600' },
        h4: { fontFamily: 'Crimson Text', fontSize: '1.125rem', fontWeight: '600' },
        body: { fontFamily: 'Crimson Text', fontSize: '1.1rem', fontWeight: '400', lineHeight: '1.75' },
        small: { fontFamily: 'Crimson Text', fontSize: '0.9rem', fontWeight: '400' },
        caption: { fontFamily: 'Oswald', fontSize: '0.7rem', fontWeight: '400', textTransform: 'uppercase', letterSpacing: '0.1em' },
      },
      fontImports: ['Oswald', 'Crimson Text'],
      spacing: { xs: '0.25rem', sm: '0.5rem', md: '1rem', lg: '2rem', xl: '4rem', '2xl': '6rem' },
      radii: { none: '0', sm: '0.125rem', md: '0.25rem', lg: '0.5rem', full: '9999px' },
      shadows: {
        none: 'none',
        sm: '0 1px 3px rgba(45,42,36,0.1)',
        md: '0 3px 10px rgba(45,42,36,0.15)',
        lg: '0 6px 20px rgba(45,42,36,0.2)',
        xl: '0 12px 36px rgba(45,42,36,0.25)',
      },
      animation: { sectionEntrance: 'fade', duration: '0.8s', easing: 'ease' },
      layout: {
        contentWidth: '60rem',
        sectionPadding: '4.5rem',
        sectionOrder: ['hero', 'bio', 'music', 'events', 'photos', 'contact'],
        sectionVisibility: { hero: true, bio: true, music: true, events: true, photos: true, contact: true },
        navStyle: 'static',
        footerStyle: 'detailed',
      },
      sections: {
        hero: { variant: 'split', overlayOpacity: 0.4, titleAlignment: 'center', showSubtitle: true, showGenres: true },
        bio: { variant: 'sidebar', showReadMore: true, maxLines: 8 },
        music: { variant: 'list', columnsDesktop: 1, showCoverArt: true, showDuration: true },
        events: { variant: 'timeline', showPastEvents: true, maxVisible: 10 },
        photos: { variant: 'carousel', columnsDesktop: 3, gap: '0.5rem', aspectRatio: 'landscape' },
        contact: { variant: 'form', showSocialLinks: true },
      },
      decorative: {
        dividerStyle: 'dots',
        backgroundPattern: 'noise',
        buttonStyle: 'square',
        linkStyle: 'underline',
        cardBorder: 'solid',
        shadow: 'sm',
      },
    },
  },

  // ── 6. Bold & Graphic ────────────────────────────────────────────────
  {
    id: 'bold-graphic',
    label: 'Bold & Graphic',
    description: 'High contrast, display fonts, geometric shapes',
    tokens: {
      colors: {
        primary: '#000000',
        secondary: '#1a1a1a',
        accent: '#ffcc00',
        background: '#ffffff',
        surface: '#f0f0f0',
        text: '#1a1a1a',
        textMuted: '#666666',
        heading: '#000000',
        link: '#ff3300',
        border: '#000000',
        error: '#ff0033',
        success: '#00cc66',
      },
      typography: {
        display: { fontFamily: 'Anton', fontSize: '6rem', fontWeight: '400', textTransform: 'uppercase', lineHeight: '0.95' },
        h1: { fontFamily: 'Anton', fontSize: '3rem', fontWeight: '400', textTransform: 'uppercase', lineHeight: '1' },
        h2: { fontFamily: 'Archivo Black', fontSize: '1.75rem', fontWeight: '400', textTransform: 'uppercase' },
        h3: { fontFamily: 'Barlow', fontSize: '1.25rem', fontWeight: '700' },
        h4: { fontFamily: 'Barlow', fontSize: '1rem', fontWeight: '700' },
        body: { fontFamily: 'Barlow', fontSize: '1rem', fontWeight: '400', lineHeight: '1.6' },
        small: { fontFamily: 'Barlow', fontSize: '0.875rem', fontWeight: '400' },
        caption: { fontFamily: 'Barlow', fontSize: '0.75rem', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.06em' },
      },
      fontImports: ['Anton', 'Archivo Black', 'Barlow'],
      spacing: { xs: '0.25rem', sm: '0.5rem', md: '1rem', lg: '2rem', xl: '4rem', '2xl': '6rem' },
      radii: { none: '0', sm: '0', md: '0', lg: '0', full: '9999px' },
      shadows: {
        none: 'none',
        sm: '2px 2px 0 #000000',
        md: '4px 4px 0 #000000',
        lg: '6px 6px 0 #000000',
        xl: '8px 8px 0 #000000',
      },
      animation: { sectionEntrance: 'scale', duration: '0.4s', easing: 'cubic-bezier(0.34,1.56,0.64,1)' },
      layout: {
        contentWidth: '76rem',
        sectionPadding: '4rem',
        sectionOrder: ['hero', 'bio', 'music', 'events', 'photos', 'contact'],
        sectionVisibility: { hero: true, bio: true, music: true, events: true, photos: true, contact: true },
        navStyle: 'fixed',
        footerStyle: 'minimal',
      },
      sections: {
        hero: { variant: 'fullscreen', overlayOpacity: 0.5, titleAlignment: 'left', showSubtitle: false, showGenres: true },
        bio: { variant: 'full-width', showReadMore: false, maxLines: 5 },
        music: { variant: 'cards', columnsDesktop: 4, showCoverArt: true, showDuration: false },
        events: { variant: 'grid', showPastEvents: false, maxVisible: 6 },
        photos: { variant: 'grid', columnsDesktop: 4, gap: '0.25rem', aspectRatio: 'square' },
        contact: { variant: 'minimal', showSocialLinks: true },
      },
      decorative: {
        dividerStyle: 'diagonal',
        backgroundPattern: 'dots',
        accentElements: {
          geometricShapes: { enabled: true, style: 'lines' },
        },
        buttonStyle: 'square',
        linkStyle: 'none',
        cardBorder: 'solid',
        shadow: 'md',
      },
    },
  },

  // ── 7. Ethereal & Ambient ────────────────────────────────────────────
  {
    id: 'ethereal-ambient',
    label: 'Ethereal & Ambient',
    description: 'Soft pastels, light backgrounds, subtle dreamy animations',
    tokens: {
      colors: {
        primary: '#6b5b95',
        secondary: '#8b7db8',
        accent: '#b8a9d1',
        background: '#f8f6fb',
        surface: '#eee8f5',
        text: '#4a4060',
        textMuted: '#9088a3',
        heading: '#3d3355',
        link: '#7c6baf',
        border: '#ddd5ea',
        error: '#d4556b',
        success: '#5aa88f',
      },
      gradients: [
        { type: 'linear', angle: 180, stops: [{ color: '#f8f6fb', position: 0 }, { color: '#eee8f5', position: 100 }] },
      ],
      typography: {
        display: { fontFamily: 'Cormorant Garamond', fontSize: '4.5rem', fontWeight: '300', lineHeight: '1.1', letterSpacing: '0.01em' },
        h1: { fontFamily: 'Cormorant Garamond', fontSize: '2.5rem', fontWeight: '400', lineHeight: '1.2' },
        h2: { fontFamily: 'Cormorant Garamond', fontSize: '1.75rem', fontWeight: '500' },
        h3: { fontFamily: 'Raleway', fontSize: '1.25rem', fontWeight: '500' },
        h4: { fontFamily: 'Raleway', fontSize: '1rem', fontWeight: '500' },
        body: { fontFamily: 'Raleway', fontSize: '1rem', fontWeight: '300', lineHeight: '1.9' },
        small: { fontFamily: 'Raleway', fontSize: '0.875rem', fontWeight: '300' },
        caption: { fontFamily: 'Raleway', fontSize: '0.75rem', fontWeight: '400', letterSpacing: '0.04em' },
      },
      fontImports: ['Cormorant Garamond', 'Raleway'],
      spacing: { xs: '0.5rem', sm: '1rem', md: '1.5rem', lg: '3rem', xl: '5rem', '2xl': '8rem' },
      radii: { none: '0', sm: '0.5rem', md: '1rem', lg: '1.5rem', full: '9999px' },
      shadows: {
        none: 'none',
        sm: '0 2px 8px rgba(107,91,149,0.06)',
        md: '0 4px 16px rgba(107,91,149,0.08)',
        lg: '0 8px 32px rgba(107,91,149,0.1)',
        xl: '0 16px 48px rgba(107,91,149,0.12)',
      },
      animation: { sectionEntrance: 'fade', duration: '1s', easing: 'ease-in-out' },
      layout: {
        contentWidth: '64rem',
        sectionPadding: '6rem',
        sectionOrder: ['hero', 'bio', 'music', 'events', 'photos', 'contact'],
        sectionVisibility: { hero: true, bio: true, music: true, events: true, photos: true, contact: true },
        navStyle: 'fixed',
        footerStyle: 'minimal',
      },
      sections: {
        hero: { variant: 'parallax', overlayOpacity: 0.2, titleAlignment: 'center', showSubtitle: true, showGenres: true },
        bio: { variant: 'centered', showReadMore: true, maxLines: 8 },
        music: { variant: 'featured', columnsDesktop: 2, showCoverArt: true, showDuration: true },
        events: { variant: 'list', showPastEvents: false, maxVisible: 5 },
        photos: { variant: 'lightbox', columnsDesktop: 3, gap: '1rem', aspectRatio: 'portrait' },
        contact: { variant: 'card', showSocialLinks: true },
      },
      decorative: {
        dividerStyle: 'wave',
        backgroundPattern: 'none',
        accentElements: {
          blur: { enabled: true, radius: '120px' },
        },
        buttonStyle: 'pill',
        linkStyle: 'hover-underline',
        cardBorder: 'none',
        shadow: 'sm',
      },
    },
  },

  // ── 8. Raw Underground ───────────────────────────────────────────────
  {
    id: 'raw-underground',
    label: 'Raw Underground',
    description: 'Dark, gritty, monospace fonts, minimal decoration',
    tokens: {
      colors: {
        primary: '#1c1c1c',
        secondary: '#262626',
        accent: '#a0a0a0',
        background: '#121212',
        surface: '#1e1e1e',
        text: '#b0b0b0',
        textMuted: '#666666',
        heading: '#e0e0e0',
        link: '#cccccc',
        border: '#333333',
        error: '#cc4444',
        success: '#44aa44',
      },
      typography: {
        display: { fontFamily: 'Space Mono', fontSize: '3.5rem', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '-0.02em' },
        h1: { fontFamily: 'Space Mono', fontSize: '2rem', fontWeight: '700', textTransform: 'uppercase' },
        h2: { fontFamily: 'Space Mono', fontSize: '1.25rem', fontWeight: '700', textTransform: 'uppercase' },
        h3: { fontFamily: 'IBM Plex Mono', fontSize: '1.1rem', fontWeight: '600' },
        h4: { fontFamily: 'IBM Plex Mono', fontSize: '0.95rem', fontWeight: '600' },
        body: { fontFamily: 'IBM Plex Mono', fontSize: '0.9rem', fontWeight: '400', lineHeight: '1.7' },
        small: { fontFamily: 'IBM Plex Mono', fontSize: '0.8rem', fontWeight: '400' },
        caption: { fontFamily: 'Space Mono', fontSize: '0.7rem', fontWeight: '400', textTransform: 'uppercase', letterSpacing: '0.08em' },
      },
      fontImports: ['Space Mono', 'IBM Plex Mono'],
      spacing: { xs: '0.25rem', sm: '0.5rem', md: '1rem', lg: '1.5rem', xl: '3rem', '2xl': '5rem' },
      radii: { none: '0', sm: '0', md: '0', lg: '0.25rem', full: '9999px' },
      shadows: {
        none: 'none',
        sm: '0 1px 2px rgba(0,0,0,0.4)',
        md: '0 2px 6px rgba(0,0,0,0.5)',
        lg: '0 4px 12px rgba(0,0,0,0.6)',
        xl: '0 8px 24px rgba(0,0,0,0.7)',
      },
      animation: { sectionEntrance: 'none' },
      layout: {
        contentWidth: '56rem',
        sectionPadding: '3rem',
        sectionOrder: ['hero', 'bio', 'music', 'events', 'photos', 'contact'],
        sectionVisibility: { hero: true, bio: true, music: true, events: true, photos: true, contact: true },
        navStyle: 'hidden',
        footerStyle: 'hidden',
      },
      sections: {
        hero: { variant: 'minimal', titleAlignment: 'left', showSubtitle: false, showGenres: true },
        bio: { variant: 'full-width', showReadMore: false, maxLines: 4 },
        music: { variant: 'list', columnsDesktop: 1, showCoverArt: false, showDuration: true },
        events: { variant: 'list', showPastEvents: false, maxVisible: 5 },
        photos: { variant: 'grid', columnsDesktop: 2, gap: '0.25rem', aspectRatio: 'landscape' },
        contact: { variant: 'minimal', showSocialLinks: true },
      },
      decorative: {
        dividerStyle: 'none',
        backgroundPattern: 'noise',
        buttonStyle: 'square',
        linkStyle: 'underline',
        cardBorder: 'subtle',
        shadow: 'none',
      },
    },
  },
]

export function getVibePreset(id: string): VibePreset | undefined {
  return VIBE_PRESETS.find((v) => v.id === id)
}
