/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as SupportCustomDomainRouteImport } from './routes/support/custom-domain'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AgencyOrgSlugRouteImport } from './routes/agency/$orgSlug'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard.index'
import { Route as DashboardDashboardThemeRouteImport } from './routes/_dashboard/dashboard.theme'
import { Route as DashboardDashboardTechnicalRouteImport } from './routes/_dashboard/dashboard.technical'
import { Route as DashboardDashboardTeamRouteImport } from './routes/_dashboard/dashboard.team'
import { Route as DashboardDashboardSocialPreviewRouteImport } from './routes/_dashboard/dashboard.social-preview'
import { Route as DashboardDashboardSettingsRouteImport } from './routes/_dashboard/dashboard.settings'
import { Route as DashboardDashboardRosterRouteImport } from './routes/_dashboard/dashboard.roster'
import { Route as DashboardDashboardProfileRouteImport } from './routes/_dashboard/dashboard.profile'
import { Route as DashboardDashboardPressRouteImport } from './routes/_dashboard/dashboard.press'
import { Route as DashboardDashboardPhotosRouteImport } from './routes/_dashboard/dashboard.photos'
import { Route as DashboardDashboardPagesRouteImport } from './routes/_dashboard/dashboard.pages'
import { Route as DashboardDashboardMusicRouteImport } from './routes/_dashboard/dashboard.music'
import { Route as DashboardDashboardHeroRouteImport } from './routes/_dashboard/dashboard.hero'
import { Route as DashboardDashboardFilesRouteImport } from './routes/_dashboard/dashboard.files'
import { Route as DashboardDashboardEventsRouteImport } from './routes/_dashboard/dashboard.events'
import { Route as DashboardDashboardContactRouteImport } from './routes/_dashboard/dashboard.contact'
import { Route as DashboardDashboardBioRouteImport } from './routes/_dashboard/dashboard.bio'
import { Route as DashboardDashboardBillingRouteImport } from './routes/_dashboard/dashboard.billing'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const SupportCustomDomainRoute = SupportCustomDomainRouteImport.update({
  id: '/support/custom-domain',
  path: '/support/custom-domain',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyOrgSlugRoute = AgencyOrgSlugRouteImport.update({
  id: '/agency/$orgSlug',
  path: '/agency/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardThemeRoute = DashboardDashboardThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardTechnicalRoute =
  DashboardDashboardTechnicalRouteImport.update({
    id: '/technical',
    path: '/technical',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardTeamRoute = DashboardDashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardSocialPreviewRoute =
  DashboardDashboardSocialPreviewRouteImport.update({
    id: '/social-preview',
    path: '/social-preview',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardSettingsRoute =
  DashboardDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardRosterRoute =
  DashboardDashboardRosterRouteImport.update({
    id: '/roster',
    path: '/roster',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardProfileRoute =
  DashboardDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardPressRoute = DashboardDashboardPressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardPhotosRoute =
  DashboardDashboardPhotosRouteImport.update({
    id: '/photos',
    path: '/photos',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardPagesRoute = DashboardDashboardPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardMusicRoute = DashboardDashboardMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardHeroRoute = DashboardDashboardHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardFilesRoute = DashboardDashboardFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardEventsRoute =
  DashboardDashboardEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardContactRoute =
  DashboardDashboardContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardBioRoute = DashboardDashboardBioRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardBillingRoute =
  DashboardDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/blog': typeof BlogRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof DashboardDashboardRouteWithChildren
  '/agency/$orgSlug': typeof AgencyOrgSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/support/custom-domain': typeof SupportCustomDomainRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/billing': typeof DashboardDashboardBillingRoute
  '/dashboard/bio': typeof DashboardDashboardBioRoute
  '/dashboard/contact': typeof DashboardDashboardContactRoute
  '/dashboard/events': typeof DashboardDashboardEventsRoute
  '/dashboard/files': typeof DashboardDashboardFilesRoute
  '/dashboard/hero': typeof DashboardDashboardHeroRoute
  '/dashboard/music': typeof DashboardDashboardMusicRoute
  '/dashboard/pages': typeof DashboardDashboardPagesRoute
  '/dashboard/photos': typeof DashboardDashboardPhotosRoute
  '/dashboard/press': typeof DashboardDashboardPressRoute
  '/dashboard/profile': typeof DashboardDashboardProfileRoute
  '/dashboard/roster': typeof DashboardDashboardRosterRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/dashboard/social-preview': typeof DashboardDashboardSocialPreviewRoute
  '/dashboard/team': typeof DashboardDashboardTeamRoute
  '/dashboard/technical': typeof DashboardDashboardTechnicalRoute
  '/dashboard/theme': typeof DashboardDashboardThemeRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/agency/$orgSlug': typeof AgencyOrgSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/support/custom-domain': typeof SupportCustomDomainRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard/billing': typeof DashboardDashboardBillingRoute
  '/dashboard/bio': typeof DashboardDashboardBioRoute
  '/dashboard/contact': typeof DashboardDashboardContactRoute
  '/dashboard/events': typeof DashboardDashboardEventsRoute
  '/dashboard/files': typeof DashboardDashboardFilesRoute
  '/dashboard/hero': typeof DashboardDashboardHeroRoute
  '/dashboard/music': typeof DashboardDashboardMusicRoute
  '/dashboard/pages': typeof DashboardDashboardPagesRoute
  '/dashboard/photos': typeof DashboardDashboardPhotosRoute
  '/dashboard/press': typeof DashboardDashboardPressRoute
  '/dashboard/profile': typeof DashboardDashboardProfileRoute
  '/dashboard/roster': typeof DashboardDashboardRosterRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/dashboard/social-preview': typeof DashboardDashboardSocialPreviewRoute
  '/dashboard/team': typeof DashboardDashboardTeamRoute
  '/dashboard/technical': typeof DashboardDashboardTechnicalRoute
  '/dashboard/theme': typeof DashboardDashboardThemeRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRouteWithChildren
  '/agency/$orgSlug': typeof AgencyOrgSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/support/custom-domain': typeof SupportCustomDomainRoute
  '/blog/': typeof BlogIndexRoute
  '/_dashboard/dashboard/billing': typeof DashboardDashboardBillingRoute
  '/_dashboard/dashboard/bio': typeof DashboardDashboardBioRoute
  '/_dashboard/dashboard/contact': typeof DashboardDashboardContactRoute
  '/_dashboard/dashboard/events': typeof DashboardDashboardEventsRoute
  '/_dashboard/dashboard/files': typeof DashboardDashboardFilesRoute
  '/_dashboard/dashboard/hero': typeof DashboardDashboardHeroRoute
  '/_dashboard/dashboard/music': typeof DashboardDashboardMusicRoute
  '/_dashboard/dashboard/pages': typeof DashboardDashboardPagesRoute
  '/_dashboard/dashboard/photos': typeof DashboardDashboardPhotosRoute
  '/_dashboard/dashboard/press': typeof DashboardDashboardPressRoute
  '/_dashboard/dashboard/profile': typeof DashboardDashboardProfileRoute
  '/_dashboard/dashboard/roster': typeof DashboardDashboardRosterRoute
  '/_dashboard/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/_dashboard/dashboard/social-preview': typeof DashboardDashboardSocialPreviewRoute
  '/_dashboard/dashboard/team': typeof DashboardDashboardTeamRoute
  '/_dashboard/dashboard/technical': typeof DashboardDashboardTechnicalRoute
  '/_dashboard/dashboard/theme': typeof DashboardDashboardThemeRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/blog'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/dashboard'
    | '/agency/$orgSlug'
    | '/auth/callback'
    | '/blog/$slug'
    | '/invite/$token'
    | '/support/custom-domain'
    | '/blog/'
    | '/dashboard/billing'
    | '/dashboard/bio'
    | '/dashboard/contact'
    | '/dashboard/events'
    | '/dashboard/files'
    | '/dashboard/hero'
    | '/dashboard/music'
    | '/dashboard/pages'
    | '/dashboard/photos'
    | '/dashboard/press'
    | '/dashboard/profile'
    | '/dashboard/roster'
    | '/dashboard/settings'
    | '/dashboard/social-preview'
    | '/dashboard/team'
    | '/dashboard/technical'
    | '/dashboard/theme'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/agency/$orgSlug'
    | '/auth/callback'
    | '/blog/$slug'
    | '/invite/$token'
    | '/support/custom-domain'
    | '/blog'
    | '/dashboard/billing'
    | '/dashboard/bio'
    | '/dashboard/contact'
    | '/dashboard/events'
    | '/dashboard/files'
    | '/dashboard/hero'
    | '/dashboard/music'
    | '/dashboard/pages'
    | '/dashboard/photos'
    | '/dashboard/press'
    | '/dashboard/profile'
    | '/dashboard/roster'
    | '/dashboard/settings'
    | '/dashboard/social-preview'
    | '/dashboard/team'
    | '/dashboard/technical'
    | '/dashboard/theme'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_dashboard'
    | '/blog'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/_dashboard/dashboard'
    | '/agency/$orgSlug'
    | '/auth/callback'
    | '/blog/$slug'
    | '/invite/$token'
    | '/support/custom-domain'
    | '/blog/'
    | '/_dashboard/dashboard/billing'
    | '/_dashboard/dashboard/bio'
    | '/_dashboard/dashboard/contact'
    | '/_dashboard/dashboard/events'
    | '/_dashboard/dashboard/files'
    | '/_dashboard/dashboard/hero'
    | '/_dashboard/dashboard/music'
    | '/_dashboard/dashboard/pages'
    | '/_dashboard/dashboard/photos'
    | '/_dashboard/dashboard/press'
    | '/_dashboard/dashboard/profile'
    | '/_dashboard/dashboard/roster'
    | '/_dashboard/dashboard/settings'
    | '/_dashboard/dashboard/social-preview'
    | '/_dashboard/dashboard/team'
    | '/_dashboard/dashboard/technical'
    | '/_dashboard/dashboard/theme'
    | '/_dashboard/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AgencyOrgSlugRoute: typeof AgencyOrgSlugRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  InviteTokenRoute: typeof InviteTokenRoute
  SupportCustomDomainRoute: typeof SupportCustomDomainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/support/custom-domain': {
      id: '/support/custom-domain'
      path: '/support/custom-domain'
      fullPath: '/support/custom-domain'
      preLoaderRoute: typeof SupportCustomDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/$orgSlug': {
      id: '/agency/$orgSlug'
      path: '/agency/$orgSlug'
      fullPath: '/agency/$orgSlug'
      preLoaderRoute: typeof AgencyOrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/theme': {
      id: '/_dashboard/dashboard/theme'
      path: '/theme'
      fullPath: '/dashboard/theme'
      preLoaderRoute: typeof DashboardDashboardThemeRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/technical': {
      id: '/_dashboard/dashboard/technical'
      path: '/technical'
      fullPath: '/dashboard/technical'
      preLoaderRoute: typeof DashboardDashboardTechnicalRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/team': {
      id: '/_dashboard/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardDashboardTeamRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/social-preview': {
      id: '/_dashboard/dashboard/social-preview'
      path: '/social-preview'
      fullPath: '/dashboard/social-preview'
      preLoaderRoute: typeof DashboardDashboardSocialPreviewRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/settings': {
      id: '/_dashboard/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardDashboardSettingsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/roster': {
      id: '/_dashboard/dashboard/roster'
      path: '/roster'
      fullPath: '/dashboard/roster'
      preLoaderRoute: typeof DashboardDashboardRosterRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/profile': {
      id: '/_dashboard/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardDashboardProfileRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/press': {
      id: '/_dashboard/dashboard/press'
      path: '/press'
      fullPath: '/dashboard/press'
      preLoaderRoute: typeof DashboardDashboardPressRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/photos': {
      id: '/_dashboard/dashboard/photos'
      path: '/photos'
      fullPath: '/dashboard/photos'
      preLoaderRoute: typeof DashboardDashboardPhotosRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/pages': {
      id: '/_dashboard/dashboard/pages'
      path: '/pages'
      fullPath: '/dashboard/pages'
      preLoaderRoute: typeof DashboardDashboardPagesRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/music': {
      id: '/_dashboard/dashboard/music'
      path: '/music'
      fullPath: '/dashboard/music'
      preLoaderRoute: typeof DashboardDashboardMusicRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/hero': {
      id: '/_dashboard/dashboard/hero'
      path: '/hero'
      fullPath: '/dashboard/hero'
      preLoaderRoute: typeof DashboardDashboardHeroRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/files': {
      id: '/_dashboard/dashboard/files'
      path: '/files'
      fullPath: '/dashboard/files'
      preLoaderRoute: typeof DashboardDashboardFilesRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/events': {
      id: '/_dashboard/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardDashboardEventsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/contact': {
      id: '/_dashboard/dashboard/contact'
      path: '/contact'
      fullPath: '/dashboard/contact'
      preLoaderRoute: typeof DashboardDashboardContactRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/bio': {
      id: '/_dashboard/dashboard/bio'
      path: '/bio'
      fullPath: '/dashboard/bio'
      preLoaderRoute: typeof DashboardDashboardBioRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/billing': {
      id: '/_dashboard/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardDashboardBillingRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
  }
}

interface DashboardDashboardRouteChildren {
  DashboardDashboardBillingRoute: typeof DashboardDashboardBillingRoute
  DashboardDashboardBioRoute: typeof DashboardDashboardBioRoute
  DashboardDashboardContactRoute: typeof DashboardDashboardContactRoute
  DashboardDashboardEventsRoute: typeof DashboardDashboardEventsRoute
  DashboardDashboardFilesRoute: typeof DashboardDashboardFilesRoute
  DashboardDashboardHeroRoute: typeof DashboardDashboardHeroRoute
  DashboardDashboardMusicRoute: typeof DashboardDashboardMusicRoute
  DashboardDashboardPagesRoute: typeof DashboardDashboardPagesRoute
  DashboardDashboardPhotosRoute: typeof DashboardDashboardPhotosRoute
  DashboardDashboardPressRoute: typeof DashboardDashboardPressRoute
  DashboardDashboardProfileRoute: typeof DashboardDashboardProfileRoute
  DashboardDashboardRosterRoute: typeof DashboardDashboardRosterRoute
  DashboardDashboardSettingsRoute: typeof DashboardDashboardSettingsRoute
  DashboardDashboardSocialPreviewRoute: typeof DashboardDashboardSocialPreviewRoute
  DashboardDashboardTeamRoute: typeof DashboardDashboardTeamRoute
  DashboardDashboardTechnicalRoute: typeof DashboardDashboardTechnicalRoute
  DashboardDashboardThemeRoute: typeof DashboardDashboardThemeRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
}

const DashboardDashboardRouteChildren: DashboardDashboardRouteChildren = {
  DashboardDashboardBillingRoute: DashboardDashboardBillingRoute,
  DashboardDashboardBioRoute: DashboardDashboardBioRoute,
  DashboardDashboardContactRoute: DashboardDashboardContactRoute,
  DashboardDashboardEventsRoute: DashboardDashboardEventsRoute,
  DashboardDashboardFilesRoute: DashboardDashboardFilesRoute,
  DashboardDashboardHeroRoute: DashboardDashboardHeroRoute,
  DashboardDashboardMusicRoute: DashboardDashboardMusicRoute,
  DashboardDashboardPagesRoute: DashboardDashboardPagesRoute,
  DashboardDashboardPhotosRoute: DashboardDashboardPhotosRoute,
  DashboardDashboardPressRoute: DashboardDashboardPressRoute,
  DashboardDashboardProfileRoute: DashboardDashboardProfileRoute,
  DashboardDashboardRosterRoute: DashboardDashboardRosterRoute,
  DashboardDashboardSettingsRoute: DashboardDashboardSettingsRoute,
  DashboardDashboardSocialPreviewRoute: DashboardDashboardSocialPreviewRoute,
  DashboardDashboardTeamRoute: DashboardDashboardTeamRoute,
  DashboardDashboardTechnicalRoute: DashboardDashboardTechnicalRoute,
  DashboardDashboardThemeRoute: DashboardDashboardThemeRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
}

const DashboardDashboardRouteWithChildren =
  DashboardDashboardRoute._addFileChildren(DashboardDashboardRouteChildren)

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  DashboardRoute: DashboardRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AgencyOrgSlugRoute: AgencyOrgSlugRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  InviteTokenRoute: InviteTokenRoute,
  SupportCustomDomainRoute: SupportCustomDomainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
