/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard.index'
import { Route as DashboardDashboardThemeRouteImport } from './routes/_dashboard/dashboard.theme'
import { Route as DashboardDashboardTechnicalRouteImport } from './routes/_dashboard/dashboard.technical'
import { Route as DashboardDashboardSocialsRouteImport } from './routes/_dashboard/dashboard.socials'
import { Route as DashboardDashboardSettingsRouteImport } from './routes/_dashboard/dashboard.settings'
import { Route as DashboardDashboardPressRouteImport } from './routes/_dashboard/dashboard.press'
import { Route as DashboardDashboardMusicRouteImport } from './routes/_dashboard/dashboard.music'
import { Route as DashboardDashboardInquiriesRouteImport } from './routes/_dashboard/dashboard.inquiries'
import { Route as DashboardDashboardEventsRouteImport } from './routes/_dashboard/dashboard.events'
import { Route as DashboardDashboardContactRouteImport } from './routes/_dashboard/dashboard.contact'
import { Route as DashboardDashboardBioRouteImport } from './routes/_dashboard/dashboard.bio'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardThemeRoute = DashboardDashboardThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardTechnicalRoute =
  DashboardDashboardTechnicalRouteImport.update({
    id: '/technical',
    path: '/technical',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardSocialsRoute =
  DashboardDashboardSocialsRouteImport.update({
    id: '/socials',
    path: '/socials',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardSettingsRoute =
  DashboardDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardPressRoute = DashboardDashboardPressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardMusicRoute = DashboardDashboardMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardInquiriesRoute =
  DashboardDashboardInquiriesRouteImport.update({
    id: '/inquiries',
    path: '/inquiries',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardEventsRoute =
  DashboardDashboardEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardContactRoute =
  DashboardDashboardContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardBioRoute = DashboardDashboardBioRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => DashboardDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof DashboardDashboardRouteWithChildren
  '/dashboard/bio': typeof DashboardDashboardBioRoute
  '/dashboard/contact': typeof DashboardDashboardContactRoute
  '/dashboard/events': typeof DashboardDashboardEventsRoute
  '/dashboard/inquiries': typeof DashboardDashboardInquiriesRoute
  '/dashboard/music': typeof DashboardDashboardMusicRoute
  '/dashboard/press': typeof DashboardDashboardPressRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/dashboard/socials': typeof DashboardDashboardSocialsRoute
  '/dashboard/technical': typeof DashboardDashboardTechnicalRoute
  '/dashboard/theme': typeof DashboardDashboardThemeRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/bio': typeof DashboardDashboardBioRoute
  '/dashboard/contact': typeof DashboardDashboardContactRoute
  '/dashboard/events': typeof DashboardDashboardEventsRoute
  '/dashboard/inquiries': typeof DashboardDashboardInquiriesRoute
  '/dashboard/music': typeof DashboardDashboardMusicRoute
  '/dashboard/press': typeof DashboardDashboardPressRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/dashboard/socials': typeof DashboardDashboardSocialsRoute
  '/dashboard/technical': typeof DashboardDashboardTechnicalRoute
  '/dashboard/theme': typeof DashboardDashboardThemeRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRouteWithChildren
  '/_dashboard/dashboard/bio': typeof DashboardDashboardBioRoute
  '/_dashboard/dashboard/contact': typeof DashboardDashboardContactRoute
  '/_dashboard/dashboard/events': typeof DashboardDashboardEventsRoute
  '/_dashboard/dashboard/inquiries': typeof DashboardDashboardInquiriesRoute
  '/_dashboard/dashboard/music': typeof DashboardDashboardMusicRoute
  '/_dashboard/dashboard/press': typeof DashboardDashboardPressRoute
  '/_dashboard/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/_dashboard/dashboard/socials': typeof DashboardDashboardSocialsRoute
  '/_dashboard/dashboard/technical': typeof DashboardDashboardTechnicalRoute
  '/_dashboard/dashboard/theme': typeof DashboardDashboardThemeRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/dashboard/bio'
    | '/dashboard/contact'
    | '/dashboard/events'
    | '/dashboard/inquiries'
    | '/dashboard/music'
    | '/dashboard/press'
    | '/dashboard/settings'
    | '/dashboard/socials'
    | '/dashboard/technical'
    | '/dashboard/theme'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/bio'
    | '/dashboard/contact'
    | '/dashboard/events'
    | '/dashboard/inquiries'
    | '/dashboard/music'
    | '/dashboard/press'
    | '/dashboard/settings'
    | '/dashboard/socials'
    | '/dashboard/technical'
    | '/dashboard/theme'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_dashboard/dashboard'
    | '/_dashboard/dashboard/bio'
    | '/_dashboard/dashboard/contact'
    | '/_dashboard/dashboard/events'
    | '/_dashboard/dashboard/inquiries'
    | '/_dashboard/dashboard/music'
    | '/_dashboard/dashboard/press'
    | '/_dashboard/dashboard/settings'
    | '/_dashboard/dashboard/socials'
    | '/_dashboard/dashboard/technical'
    | '/_dashboard/dashboard/theme'
    | '/_dashboard/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/theme': {
      id: '/_dashboard/dashboard/theme'
      path: '/theme'
      fullPath: '/dashboard/theme'
      preLoaderRoute: typeof DashboardDashboardThemeRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/technical': {
      id: '/_dashboard/dashboard/technical'
      path: '/technical'
      fullPath: '/dashboard/technical'
      preLoaderRoute: typeof DashboardDashboardTechnicalRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/socials': {
      id: '/_dashboard/dashboard/socials'
      path: '/socials'
      fullPath: '/dashboard/socials'
      preLoaderRoute: typeof DashboardDashboardSocialsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/settings': {
      id: '/_dashboard/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardDashboardSettingsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/press': {
      id: '/_dashboard/dashboard/press'
      path: '/press'
      fullPath: '/dashboard/press'
      preLoaderRoute: typeof DashboardDashboardPressRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/music': {
      id: '/_dashboard/dashboard/music'
      path: '/music'
      fullPath: '/dashboard/music'
      preLoaderRoute: typeof DashboardDashboardMusicRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/inquiries': {
      id: '/_dashboard/dashboard/inquiries'
      path: '/inquiries'
      fullPath: '/dashboard/inquiries'
      preLoaderRoute: typeof DashboardDashboardInquiriesRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/events': {
      id: '/_dashboard/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardDashboardEventsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/contact': {
      id: '/_dashboard/dashboard/contact'
      path: '/contact'
      fullPath: '/dashboard/contact'
      preLoaderRoute: typeof DashboardDashboardContactRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/bio': {
      id: '/_dashboard/dashboard/bio'
      path: '/bio'
      fullPath: '/dashboard/bio'
      preLoaderRoute: typeof DashboardDashboardBioRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
  }
}

interface DashboardDashboardRouteChildren {
  DashboardDashboardBioRoute: typeof DashboardDashboardBioRoute
  DashboardDashboardContactRoute: typeof DashboardDashboardContactRoute
  DashboardDashboardEventsRoute: typeof DashboardDashboardEventsRoute
  DashboardDashboardInquiriesRoute: typeof DashboardDashboardInquiriesRoute
  DashboardDashboardMusicRoute: typeof DashboardDashboardMusicRoute
  DashboardDashboardPressRoute: typeof DashboardDashboardPressRoute
  DashboardDashboardSettingsRoute: typeof DashboardDashboardSettingsRoute
  DashboardDashboardSocialsRoute: typeof DashboardDashboardSocialsRoute
  DashboardDashboardTechnicalRoute: typeof DashboardDashboardTechnicalRoute
  DashboardDashboardThemeRoute: typeof DashboardDashboardThemeRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
}

const DashboardDashboardRouteChildren: DashboardDashboardRouteChildren = {
  DashboardDashboardBioRoute: DashboardDashboardBioRoute,
  DashboardDashboardContactRoute: DashboardDashboardContactRoute,
  DashboardDashboardEventsRoute: DashboardDashboardEventsRoute,
  DashboardDashboardInquiriesRoute: DashboardDashboardInquiriesRoute,
  DashboardDashboardMusicRoute: DashboardDashboardMusicRoute,
  DashboardDashboardPressRoute: DashboardDashboardPressRoute,
  DashboardDashboardSettingsRoute: DashboardDashboardSettingsRoute,
  DashboardDashboardSocialsRoute: DashboardDashboardSocialsRoute,
  DashboardDashboardTechnicalRoute: DashboardDashboardTechnicalRoute,
  DashboardDashboardThemeRoute: DashboardDashboardThemeRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
}

const DashboardDashboardRouteWithChildren =
  DashboardDashboardRoute._addFileChildren(DashboardDashboardRouteChildren)

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
